/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.Resistencia;
import java.awt.Color;

/**
 *
 * @author User
 */
public class GUIResistencia extends javax.swing.JFrame {

    /**
     * Creates new form GUIResistencia
     */
    public GUIResistencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBanda1 = new javax.swing.JLabel();
        lbBanda2 = new javax.swing.JLabel();
        lbBanda3 = new javax.swing.JLabel();
        lbMultiplicador = new javax.swing.JLabel();
        lbTolerancia = new javax.swing.JLabel();
        cbxBanda1 = new javax.swing.JComboBox<>();
        cbxBanda2 = new javax.swing.JComboBox<>();
        cbxBanda3 = new javax.swing.JComboBox<>();
        cbxMultiplicador = new javax.swing.JComboBox<>();
        cbxTolerancia = new javax.swing.JComboBox<>();
        lbColorBanda1 = new javax.swing.JLabel();
        lbColorBanda2 = new javax.swing.JLabel();
        lbColorBanda3 = new javax.swing.JLabel();
        lbColorMultiplicador = new javax.swing.JLabel();
        lbColorTolerancia = new javax.swing.JLabel();
        lbResistencia = new javax.swing.JLabel();
        lbMSGResistencia = new javax.swing.JLabel();
        lbValorResistencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBanda1.setText("BANDA 1:");
        jPanel1.add(lbBanda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));

        lbBanda2.setText("BANDA 2:");
        jPanel1.add(lbBanda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, -1, -1));

        lbBanda3.setText("BANDA 3:");
        jPanel1.add(lbBanda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, -1, -1));

        lbMultiplicador.setText("MULTIPLICADOR");
        jPanel1.add(lbMultiplicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, -1, -1));

        lbTolerancia.setText("TOLERANCIA");
        jPanel1.add(lbTolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, -1, -1));

        cbxBanda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un color", "Negro", "Marron", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        cbxBanda1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxBanda1ItemStateChanged(evt);
            }
        });
        jPanel1.add(cbxBanda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, -1, -1));

        cbxBanda2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un color", "Negro", "Marron", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        cbxBanda2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxBanda2ItemStateChanged(evt);
            }
        });
        jPanel1.add(cbxBanda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, -1, -1));

        cbxBanda3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un color", "Negro", "Marron", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        cbxBanda3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxBanda3ItemStateChanged(evt);
            }
        });
        jPanel1.add(cbxBanda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, -1, -1));

        cbxMultiplicador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un color", "Negro", "Marron", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Dorado", "Plateado" }));
        cbxMultiplicador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMultiplicadorItemStateChanged(evt);
            }
        });
        jPanel1.add(cbxMultiplicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 199, -1, -1));

        cbxTolerancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un color", "Marron", "Rojo", "Verde", "Azul", "Violeta", "Gris", "Dorado", "Plateado" }));
        cbxTolerancia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxToleranciaItemStateChanged(evt);
            }
        });
        jPanel1.add(cbxTolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 253, -1, -1));

        lbColorBanda1.setOpaque(true);
        jPanel1.add(lbColorBanda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 31, 21, 72));
        lbColorBanda1.getAccessibleContext().setAccessibleDescription("");

        lbColorBanda2.setOpaque(true);
        jPanel1.add(lbColorBanda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 41, 21, 52));

        lbColorBanda3.setOpaque(true);
        jPanel1.add(lbColorBanda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 41, 21, 52));

        lbColorMultiplicador.setOpaque(true);
        jPanel1.add(lbColorMultiplicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 41, 21, 52));

        lbColorTolerancia.setOpaque(true);
        jPanel1.add(lbColorTolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 31, 21, 72));

        lbResistencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\colorResistencia\\folder\\resistencia.png")); // NOI18N
        lbResistencia.setText("jLabel1");
        jPanel1.add(lbResistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 6, 351, 130));

        lbMSGResistencia.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbMSGResistencia.setText("Valor de la Resistencia:");
        jPanel1.add(lbMSGResistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        lbValorResistencia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(lbValorResistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxBanda1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxBanda1ItemStateChanged
        String color = cbxBanda1.getSelectedItem().toString();
        if (color.equals("Negro")) {
            lbColorBanda1.setBackground(Color.black);
        }
        if (color.equals("Marron")) {
            lbColorBanda1.setBackground(Color.decode("#8D4925"));
        }
        if (color.equals("Rojo")) {
            lbColorBanda1.setBackground(Color.red);
        }
        if (color.equals("Naranja")) {
            lbColorBanda1.setBackground(Color.orange);
        }
        if (color.equals("Amarillo")) {
            lbColorBanda1.setBackground(Color.yellow);
        }
        if (color.equals("Verde")) {
            lbColorBanda1.setBackground(Color.green);
        }
        if (color.equals("Azul")) {
            lbColorBanda1.setBackground(Color.blue);
        }
        if (color.equals("Violeta")) {
            lbColorBanda1.setBackground(Color.decode("#4c2882"));
        }
        if (color.equals("Gris")) {
            lbColorBanda1.setBackground(Color.gray);
        }
        if (color.equals("Blanco")) {
            lbColorBanda1.setBackground(Color.white);
        }
        if (color.equals("Seleccione un color")) {
            lbColorBanda1.setBackground(Color.decode("#d6d9df"));
        }
        valorResistencia();
    }//GEN-LAST:event_cbxBanda1ItemStateChanged

    private void cbxBanda2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxBanda2ItemStateChanged
        String color = cbxBanda2.getSelectedItem().toString();
        if (color.equals("Negro")) {
            lbColorBanda2.setBackground(Color.black);
        }
        if (color.equals("Marron")) {
            lbColorBanda2.setBackground(Color.decode("#8D4925"));
        }
        if (color.equals("Rojo")) {
            lbColorBanda2.setBackground(Color.red);
        }
        if (color.equals("Naranja")) {
            lbColorBanda2.setBackground(Color.orange);
        }
        if (color.equals("Amarillo")) {
            lbColorBanda2.setBackground(Color.yellow);
        }
        if (color.equals("Verde")) {
            lbColorBanda2.setBackground(Color.green);
        }
        if (color.equals("Azul")) {
            lbColorBanda2.setBackground(Color.blue);
        }
        if (color.equals("Violeta")) {
            lbColorBanda2.setBackground(Color.decode("#4c2882"));
        }
        if (color.equals("Gris")) {
            lbColorBanda2.setBackground(Color.gray);
        }
        if (color.equals("Blanco")) {
            lbColorBanda2.setBackground(Color.white);
        }
        if (color.equals("Seleccione un color")) {
            lbColorBanda2.setBackground(Color.decode("#d6d9df"));
        }
        valorResistencia();
    }//GEN-LAST:event_cbxBanda2ItemStateChanged

    private void cbxBanda3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxBanda3ItemStateChanged
        String color = cbxBanda3.getSelectedItem().toString();
        if (color.equals("Negro")) {
            lbColorBanda3.setBackground(Color.black);
        }
        if (color.equals("Marron")) {
            lbColorBanda3.setBackground(Color.decode("#8D4925"));
        }
        if (color.equals("Rojo")) {
            lbColorBanda3.setBackground(Color.red);
        }
        if (color.equals("Naranja")) {
            lbColorBanda3.setBackground(Color.orange);
        }
        if (color.equals("Amarillo")) {
            lbColorBanda3.setBackground(Color.yellow);
        }
        if (color.equals("Verde")) {
            lbColorBanda3.setBackground(Color.green);
        }
        if (color.equals("Azul")) {
            lbColorBanda3.setBackground(Color.blue);
        }
        if (color.equals("Violeta")) {
            lbColorBanda3.setBackground(Color.decode("#4c2882"));
        }
        if (color.equals("Gris")) {
            lbColorBanda3.setBackground(Color.gray);
        }
        if (color.equals("Blanco")) {
            lbColorBanda3.setBackground(Color.white);
        }
        if (color.equals("Seleccione un color")) {
            lbColorBanda3.setBackground(Color.decode("#d6d9df"));
        }
        valorResistencia();
    }//GEN-LAST:event_cbxBanda3ItemStateChanged

    private void cbxMultiplicadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMultiplicadorItemStateChanged
        String color = cbxMultiplicador.getSelectedItem().toString();
        if (color.equals("Negro")) {
            lbColorMultiplicador.setBackground(Color.black);
        }
        if (color.equals("Marron")) {
            lbColorMultiplicador.setBackground(Color.decode("#8D4925"));
        }
        if (color.equals("Rojo")) {
            lbColorMultiplicador.setBackground(Color.red);
        }
        if (color.equals("Naranja")) {
            lbColorMultiplicador.setBackground(Color.orange);
        }
        if (color.equals("Amarillo")) {
            lbColorMultiplicador.setBackground(Color.yellow);
        }
        if (color.equals("Verde")) {
            lbColorMultiplicador.setBackground(Color.green);
        }
        if (color.equals("Azul")) {
            lbColorMultiplicador.setBackground(Color.blue);
        }
        if (color.equals("Violeta")) {
            lbColorMultiplicador.setBackground(Color.decode("#4c2882"));
        }
        if (color.equals("Dorado")) {
            lbColorMultiplicador.setBackground(Color.decode("#efb810"));
        }
        if (color.equals("Plateado")) {
            lbColorMultiplicador.setBackground(Color.decode("#a3a2a0"));
        }
        if (color.equals("Seleccione un color")) {
            lbColorMultiplicador.setBackground(Color.decode("#d6d9df"));
        }
        valorResistencia();
    }//GEN-LAST:event_cbxMultiplicadorItemStateChanged

    private void cbxToleranciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxToleranciaItemStateChanged
        String color = cbxTolerancia.getSelectedItem().toString();
        if (color.equals("Marron")) {
            lbColorTolerancia.setBackground(Color.decode("#8D4925"));
        }
        if (color.equals("Rojo")) {
            lbColorTolerancia.setBackground(Color.red);
        }
        if (color.equals("Verde")) {
            lbColorTolerancia.setBackground(Color.green);
        }
        if (color.equals("Azul")) {
            lbColorTolerancia.setBackground(Color.blue);
        }
        if (color.equals("Violeta")) {
            lbColorTolerancia.setBackground(Color.decode("#4c2882"));
        }
        if (color.equals("Gris")) {
            lbColorTolerancia.setBackground(Color.gray);
        }
        if (color.equals("Dorado")) {
            lbColorTolerancia.setBackground(Color.decode("#efb810"));
        }
        if (color.equals("Plateado")) {
            lbColorTolerancia.setBackground(Color.decode("#a3a2a0"));
        }
        if (color.equals("Seleccione un color")) {
            lbColorTolerancia.setBackground(Color.decode("#d6d9df"));
        }
        valorResistencia();
    }//GEN-LAST:event_cbxToleranciaItemStateChanged

    public void valorResistencia() {
        int banda1 = 0, banda2 = 0, banda3 = 0;
        double multiplicador = 0, tolerancia = 0, valor = 0;
        String resultado = "";
        Resistencia resistencia = new Resistencia();
        if (!cbxBanda1.getSelectedItem().toString().equals("Seleccione un color") && !cbxBanda2.getSelectedItem().toString().equals("Seleccione un color")
                && !cbxBanda3.getSelectedItem().toString().equals("Seleccione un color") && !cbxMultiplicador.getSelectedItem().toString().equals("Seleccione un color")) {
            banda1 = resistencia.obtenerValor(cbxBanda1.getSelectedItem().toString());
            banda2 = resistencia.obtenerValor(cbxBanda2.getSelectedItem().toString());
            banda3 = resistencia.obtenerValor(cbxBanda3.getSelectedItem().toString());
            multiplicador = resistencia.obtenerMultiplicador(cbxMultiplicador.getSelectedItem().toString());
            tolerancia = resistencia.obtenerTolerancia(cbxTolerancia.getSelectedItem().toString());
            valor = ((banda1 * 100) + (banda2 * 10) + banda3) * multiplicador;
            resultado=valor+" Ohms "+tolerancia+"%";
            lbValorResistencia.setText(resultado);
        }else
            lbValorResistencia.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIResistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIResistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIResistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIResistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIResistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxBanda1;
    private javax.swing.JComboBox<String> cbxBanda2;
    private javax.swing.JComboBox<String> cbxBanda3;
    private javax.swing.JComboBox<String> cbxMultiplicador;
    private javax.swing.JComboBox<String> cbxTolerancia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBanda1;
    private javax.swing.JLabel lbBanda2;
    private javax.swing.JLabel lbBanda3;
    private javax.swing.JLabel lbColorBanda1;
    private javax.swing.JLabel lbColorBanda2;
    private javax.swing.JLabel lbColorBanda3;
    private javax.swing.JLabel lbColorMultiplicador;
    private javax.swing.JLabel lbColorTolerancia;
    private javax.swing.JLabel lbMSGResistencia;
    private javax.swing.JLabel lbMultiplicador;
    private javax.swing.JLabel lbResistencia;
    private javax.swing.JLabel lbTolerancia;
    private javax.swing.JLabel lbValorResistencia;
    // End of variables declaration//GEN-END:variables
}
